### PR TITLE
fixed /msg_box

### PR DESCRIPTION
**Pull request by mvrozanti**
MessageBoxA needed to be changed to MessageBoxW.

When I did only that, the title of the message box was in chinese. Added u (for unicode) just before the 'Information' string and now looks like it works.

Edited for clarity.

### CODE REVIEW

**Comment by mvrozanti** [comment]
This is my first fork/pull-request please tell me if I'm doing something wrong

**Comment by ritiek** [comment]
@mvrozanti Thank you! Everything looks good. Thank you once again :D

**Comment by CampBlanc** [comment]
Hello guys, sorry for bothering you here with this but I have a question and hope you are willing to help me out with it, would be much appreciated!

I'm receiving a keyError after starting the script and has to do with the bot token.

Please hit me up at https://t.me/AssasNin

Thank you

**Comment by mvrozanti** [comment]
@Patrickology Hey bro. @Ritiek has discontinued this project but you can still get an [updated version here](https://github.com/mvrozanti/RAT-via-Telegram). Feel free to submit an issue to the repo I just linked if the problem continues.

**Comment by CampBlanc** [comment]
Thanks bro bro, that one I found, followed the steps (I think I did it right) but get the error. Anyway I posted a screenshot, have a look :-)

**Pull request merged**
